# Introduction to Numpy

In [65]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

In [66]:
#create an array 

hamoye = np.array([2,3,5,7,9,11])

In [67]:
hamoye

array([ 2,  3,  5,  7,  9, 11])

In [68]:
type(hamoye)

numpy.ndarray

# Slice through arrays

In [69]:
hamoye[:3]

array([2, 3, 5])

In [70]:
hamoye[3:]

array([ 7,  9, 11])

In [71]:
hamoye[2:4]

array([5, 7])

In [72]:
hamoye[3:5]

array([7, 9])

In [73]:
hamoye[4]

9

In [74]:
hamoye[4] = 26
hamoye

array([ 2,  3,  5,  7, 26, 11])

# Two Dimensional Array

In [75]:
hamoye_2 = np.array([[1,3,5,7], [2,4,6,8]])

In [76]:
hamoye_2

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [77]:
hamoye_2[1,2]

6

In [78]:
hamoye_2[1,0]

2

In [79]:
hamoye_2[0,:]

array([1, 3, 5, 7])

In [80]:
hamoye_2[:,2]

array([5, 6])

In [81]:
hamoye_2[:-1,:-2]

array([[1, 3]])

In [82]:
hamoye_2[-1:,-2:]

array([[6, 8]])

In [83]:
hamoye_2.shape

(2, 4)

In [84]:
hamoye_2.ndim

2

In [85]:
hamoye_2.dtype

dtype('int32')

In [86]:
len(hamoye_2)

2

# the "in" statement for np arrays 

In [87]:
23 in hamoye_2

False

In [88]:
8 in hamoye_2

True

In [89]:
hamoye_range = np.array(range(20), float)

In [90]:
hamoye_range

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [92]:
hamoye_range = hamoye_range.reshape((5,4))

In [93]:
hamoye_range 

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [94]:
hamoye_range.shape

(5, 4)

In [95]:
hamoye_range.reshape((10,2))

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.],
       [12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.]])

In [96]:
hamoye_range.reshape((4,5))

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [97]:
a = np.array([1,2,3,4], float)

In [99]:
a

array([1., 2., 3., 4.])

In [98]:
a.tolist()

[1.0, 2.0, 3.0, 4.0]

In [100]:
list(a)

[1.0, 2.0, 3.0, 4.0]

In [101]:
a.fill(0)

In [102]:
a

array([0., 0., 0., 0.])

In [103]:
hamoye_range = np.array(range(20), float).reshape(5,4)

In [104]:
hamoye_range

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [105]:
hamoye_range.transpose()

array([[ 0.,  4.,  8., 12., 16.],
       [ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.]])

In [106]:
hamoye_range.flatten()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

## Array concatenation

In [107]:
a = np.array([3,5,7], float)
b = np.array([1,11], float)
c = np.array([5,8,9], float)

np.concatenate((a,b,c))

array([ 3.,  5.,  7.,  1., 11.,  5.,  8.,  9.])

In [108]:
x = np.array([[1,2,3], [4,7,9]], float)
y = np.array([[10,12,13], [14,17,19]], float)

In [109]:
np.concatenate((x,y))

array([[ 1.,  2.,  3.],
       [ 4.,  7.,  9.],
       [10., 12., 13.],
       [14., 17., 19.]])

In [110]:
np.concatenate((x,y), axis = 0)

array([[ 1.,  2.,  3.],
       [ 4.,  7.,  9.],
       [10., 12., 13.],
       [14., 17., 19.]])

In [113]:
np.concatenate((x,y), axis = 1)

array([[ 1.,  2.,  3., 10., 12., 13.],
       [ 4.,  7.,  9., 14., 17., 19.]])

# Other Creative ways of creating an array

In [115]:
np.arange(20, dtype = float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [116]:
np.arange(1,20,3, dtype = float)

array([ 1.,  4.,  7., 10., 13., 16., 19.])

In [117]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [118]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [119]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [120]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Special 2D arrays

In [121]:
np.identity(5, dtype = float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [123]:
np.eye(5, k=-2, dtype = float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [124]:
np.identity(3, dtype = float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
np.eye(3, k=-1, dtype = float)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [126]:
np.eye(3, k=1, dtype = float)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [127]:
np.eye(5, k=2, dtype = float)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Array Mathematics

In [129]:
a = np.array([3,5,7], float)
b = np.array([1,11,13], float)
c = np.array([5,8,9], float)

In [130]:
a+b+c

array([ 9., 24., 29.])

In [131]:
a-c

array([-2., -3., -2.])

In [132]:
a*b

array([ 3., 55., 91.])

In [133]:
b / c

array([0.2       , 1.375     , 1.44444444])

#  Python - Numpy Broadcasting

In [137]:
a = np.array([[1,3], [0,5], [2,-1]], float)

In [138]:
b = np.array([1,11], float)

In [139]:
a + b

array([[ 2., 14.],
       [ 1., 16.],
       [ 3., 10.]])

# Floor, Ceil and Rint

#### Floor gives the lower integer, Ceil gives the upper integer and rint rounds up

In [144]:
z = np.array([6.7, 2.3, 5.4,1.192], float)
z

array([6.7  , 2.3  , 5.4  , 1.192])

In [145]:
np.floor(z)

array([6., 2., 5., 1.])

In [146]:
np.ceil(z)

array([7., 3., 6., 2.])

In [147]:
np.rint(z)

array([7., 2., 5., 1.])

In [148]:
np.e

2.718281828459045

In [149]:
np.pi

3.141592653589793

# Array Iteration

In [150]:
m = np.array([1,2,5,7,8], float)
m

array([1., 2., 5., 7., 8.])

In [151]:
for hamoye in m:
    print(hamoye)

1.0
2.0
5.0
7.0
8.0


In [152]:
n = np.array([[1,3], [0,5], [2,-1]], float)
n

array([[ 1.,  3.],
       [ 0.,  5.],
       [ 2., -1.]])

In [153]:
for hamoye in n:
    print(hamoye)

[1. 3.]
[0. 5.]
[ 2. -1.]


In [154]:
for (a,b) in n:
    print(a*b)

3.0
0.0
-2.0


In [155]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [156]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [159]:
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [160]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [162]:
e = np.full((2,2), 7)
e

array([[7, 7],
       [7, 7]])

In [164]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [165]:
np.empty((3,2))

array([[ 1.,  3.],
       [ 0.,  5.],
       [ 2., -1.]])

In [166]:
np.random.random((2,2))

array([[0.83063733, 0.39765522],
       [0.72072134, 0.97196781]])